delete TB_INCONVINIENCE_BOARD_REPLY;
delete tb_inconvinience_board;
-- 10개의 더미 데이터 삽입 (컬럼을 지정하지 않고, STATUS에 랜덤으로 1부터 3까지, WRITER에 랜덤으로 1부터 10까지의 값 삽입)
INSERT INTO TB_INCONVINIENCE_BOARD 
VALUES 
(INCONVINIENCE_SEQ.NEXTVAL, 1, '장시간 대기열로 인한 불편', '오랜 대기 시간으로 인한 불편을 공유합니다.', SYSDATE - 10, SYSDATE, 1);

INSERT INTO TB_INCONVINIENCE_BOARD 
VALUES 
(INCONVINIENCE_SEQ.NEXTVAL, 2, '매장 내 청결도 저하', '매장 내 청결 상태가 저하되어 있어 불편합니다.', SYSDATE - 9, SYSDATE, 2);

INSERT INTO TB_INCONVINIENCE_BOARD 
VALUES 
(INCONVINIENCE_SEQ.NEXTVAL, 3, '제품 불량으로 인한 교환 어려움', '구매한 제품이 불량이라 교환하려고 하니 어려움이 있습니다.', SYSDATE - 8, SYSDATE, 3);

INSERT INTO TB_INCONVINIENCE_BOARD 
VALUES 
(INCONVINIENCE_SEQ.NEXTVAL, 4, '매장 내 가격표 미표시', '상품의 가격표가 미표시되어 있어 가격을 확인하기 어렵습니다.', SYSDATE - 7, SYSDATE, 1);

INSERT INTO TB_INCONVINIENCE_BOARD 
VALUES 
(INCONVINIENCE_SEQ.NEXTVAL, 5, '서비스 태도 불만', '매장 직원의 서비스 태도가 불만족스럽습니다.', SYSDATE - 6, SYSDATE, 2);

INSERT INTO TB_INCONVINIENCE_BOARD 
VALUES 
(INCONVINIENCE_SEQ.NEXTVAL, 6, '매장 내 장애물 증가', '매장 내 장애물이 늘어나서 이동하기 어려워졌습니다.', SYSDATE - 5, SYSDATE, 3);

INSERT INTO TB_INCONVINIENCE_BOARD 
VALUES 
(INCONVINIENCE_SEQ.NEXTVAL, 7, '환불 처리 지연', '상품 환불 처리가 지연되어 있어 불편합니다.', SYSDATE - 4, SYSDATE, 1);

INSERT INTO TB_INCONVINIENCE_BOARD 
VALUES 
(INCONVINIENCE_SEQ.NEXTVAL, 8, '온라인 주문 오류', '온라인 주문 시스템에서 오류가 발생하여 주문이 어려워졌습니다.', SYSDATE - 3, SYSDATE, 2);

INSERT INTO TB_INCONVINIENCE_BOARD 
VALUES 
(INCONVINIENCE_SEQ.NEXTVAL, 9, '주차장 혼잡', '매장 주변 주차장이 혼잡하여 주차하기 어렵습니다.', SYSDATE - 2, SYSDATE, 3);

INSERT INTO TB_INCONVINIENCE_BOARD 
VALUES 
(INCONVINIENCE_SEQ.NEXTVAL, 10, '매장 내 냄새', '매장 내부에서 불쾌한 냄새가 나서 불편합니다.', SYSDATE - 1, SYSDATE, 1);

-- 10개의 더미 데이터 추가
INSERT INTO TB_INCONVINIENCE_BOARD 
VALUES 
(INCONVINIENCE_SEQ.NEXTVAL, 1, '결제 시스템 오작동', '매장 내 결제 시스템이 작동하지 않아 결제가 어렵습니다.', SYSDATE - 10, SYSDATE, 2);

INSERT INTO TB_INCONVINIENCE_BOARD 
VALUES 
(INCONVINIENCE_SEQ.NEXTVAL, 2, '반품 처리 지연', '상품 반품 처리가 오랜 시간이 걸려 불편합니다.', SYSDATE - 9, SYSDATE, 3);

INSERT INTO TB_INCONVINIENCE_BOARD 
VALUES 
(INCONVINIENCE_SEQ.NEXTVAL, 3, '상품 배송 지연', '인터넷 주문한 상품의 배송이 예정보다 늦어져 불편합니다.', SYSDATE - 8, SYSDATE, 1);

INSERT INTO TB_INCONVINIENCE_BOARD 
VALUES 
(INCONVINIENCE_SEQ.NEXTVAL, 4, '매장 내 주차장 부족', '매장 주변 주차장이 부족하여 주차하기 어렵습니다.', SYSDATE - 7, SYSDATE, 2);

INSERT INTO TB_INCONVINIENCE_BOARD 
VALUES 
(INCONVINIENCE_SEQ.NEXTVAL, 5, '제품 설명 미흡', '구매한 제품의 설명이 부족하여 사용법을 알기 어렵습니다.', SYSDATE - 6, SYSDATE, 3);

INSERT INTO TB_INCONVINIENCE_BOARD 
VALUES 
(INCONVINIENCE_SEQ.NEXTVAL, 6, '매장 내 음악 소리 큼', '매장 내에서 틀어지는 음악이 너무 시끄럽습니다.', SYSDATE - 5, SYSDATE, 1);

INSERT INTO TB_INCONVINIENCE_BOARD 
VALUES 
(INCONVINIENCE_SEQ.NEXTVAL, 7, '장바구니 기능 오류', '온라인 쇼핑몰에서 장바구니에 상품을 담을 때 오류가 발생합니다.', SYSDATE - 4, SYSDATE, 2);

INSERT INTO TB_INCONVINIENCE_BOARD 
VALUES 
(INCONVINIENCE_SEQ.NEXTVAL, 8, '상품 포장 미흡', '구매한 상품의 포장이 미흡하여 상품이 손상될 우려가 있습니다.', SYSDATE - 3, SYSDATE, 3);

INSERT INTO TB_INCONVINIENCE_BOARD 
VALUES 
(INCONVINIENCE_SEQ.NEXTVAL, 9, '매장 내 온도 조절 미흡', '매장 내 온도가 너무 높아서 불편합니다.', SYSDATE - 2, SYSDATE, 1);

INSERT INTO TB_INCONVINIENCE_BOARD 
VALUES 
(INCONVINIENCE_SEQ.NEXTVAL, 10, '매장 내 화장실 청결상태 불량', '매장 내 화장실이 청결하지 않아 사용하기 불편합니다.', SYSDATE - 1, SYSDATE, 2);

-- 10개의 더미 데이터 추가
INSERT INTO TB_INCONVINIENCE_BOARD 
VALUES 
(INCONVINIENCE_SEQ.NEXTVAL, 1, '상품 포장 부실', '구매한 상품의 포장이 부실하여 상품이 손상되었습니다.', SYSDATE - 10, SYSDATE, 3);

INSERT INTO TB_INCONVINIENCE_BOARD 
VALUES 
(INCONVINIENCE_SEQ.NEXTVAL, 2, '영수증 출력 지연', '매장에서 영수증 출력이 지연되어 있어 불편합니다.', SYSDATE - 9, SYSDATE, 1);

INSERT INTO TB_INCONVINIENCE_BOARD 
VALUES 
(INCONVINIENCE_SEQ.NEXTVAL, 3, '상품정보 미표기', '상품에 대한 정보가 불분명하여 선택에 어려움이 있습니다.', SYSDATE - 8, SYSDATE, 2);

INSERT INTO TB_INCONVINIENCE_BOARD 
VALUES 
(INCONVINIENCE_SEQ.NEXTVAL, 4, '매장 내 조명 부실', '매장 내 일부 구역의 조명이 부실하여 어둡습니다.', SYSDATE - 7, SYSDATE, 3);

INSERT INTO TB_INCONVINIENCE_BOARD 
VALUES 
(INCONVINIENCE_SEQ.NEXTVAL, 5, '매장 내 가격 오류', '매장 내 상품 가격표가 틀렸습니다.', SYSDATE - 6, SYSDATE, 1);

INSERT INTO TB_INCONVINIENCE_BOARD 
VALUES 
(INCONVINIENCE_SEQ.NEXTVAL, 6, '장바구니 기능 미작동', '온라인 쇼핑몰에서 장바구니에 상품을 담을 수 없습니다.', SYSDATE - 5, SYSDATE, 2);

INSERT INTO TB_INCONVINIENCE_BOARD 
VALUES 
(INCONVINIENCE_SEQ.NEXTVAL, 7, '상품 미리보기 기능 오류', '온라인 쇼핑몰에서 상품 미리보기 기능이 작동하지 않습니다.', SYSDATE - 4, SYSDATE, 3);

INSERT INTO TB_INCONVINIENCE_BOARD 
VALUES 
(INCONVINIENCE_SEQ.NEXTVAL, 8, '배송 지연', '인터넷 주문한 상품의 배송이 예정보다 늦어져 불편합니다.', SYSDATE - 3, SYSDATE, 1);

INSERT INTO TB_INCONVINIENCE_BOARD 
VALUES 
(INCONVINIENCE_SEQ.NEXTVAL, 9, '매장 내 공간 활용 부족', '매장 내 공간이 협소하여 불편합니다.', SYSDATE - 2, SYSDATE, 2);

INSERT INTO TB_INCONVINIENCE_BOARD 
VALUES 
(INCONVINIENCE_SEQ.NEXTVAL, 10, '매장 내 무선 인터넷 불안정', '매장 내 무선 인터넷 연결이 불안정하여 사용하기 어렵습니다.', SYSDATE - 1, SYSDATE, 3);

--------------댓글
-- status가 3인 게시글에 댓글 작성
INSERT INTO TB_INCONVINIENCE_BOARD_REPLY (BOARD_NO, WRITER, WRITE_DATE, COMMENT_CONTENT) VALUES 
(29, 1000, SYSDATE - 1, '불편사항이 해결되어 기쁘게 생각합니다. 감사합니다.');
INSERT INTO TB_INCONVINIENCE_BOARD_REPLY (BOARD_NO, WRITER, WRITE_DATE, COMMENT_CONTENT) VALUES 
(11, 1001, SYSDATE - 4, '해당 불편사항이 해결되었습니다. 감사합니다.');
INSERT INTO TB_INCONVINIENCE_BOARD_REPLY (BOARD_NO, WRITER, WRITE_DATE, COMMENT_CONTENT) VALUES 
(12, 1002, SYSDATE - 5, '해당 사안은 해결되었습니다.');

-- status가 2인 게시글에 대해 "조치 중" 댓글 작성
INSERT INTO TB_INCONVINIENCE_BOARD_REPLY (BOARD_NO, WRITER, WRITE_DATE, COMMENT_CONTENT) VALUES 
(2, 1003, SYSDATE - 2, '조치 중입니다. 최대한 빨리 해결하도록 하겠습니다.');
INSERT INTO TB_INCONVINIENCE_BOARD_REPLY (BOARD_NO, WRITER, WRITE_DATE, COMMENT_CONTENT) VALUES 
(30, 1004, SYSDATE - 3, '빠른 시일 내에 조치할 수 있도록 노력하겠습니다.');
INSERT INTO TB_INCONVINIENCE_BOARD_REPLY (BOARD_NO, WRITER, WRITE_DATE, COMMENT_CONTENT) VALUES 
(6, 1005, SYSDATE - 4, '조치 중입니다. 불편을 드려 죄송합니다.');
INSERT INTO TB_INCONVINIENCE_BOARD_REPLY (BOARD_NO, WRITER, WRITE_DATE, COMMENT_CONTENT) VALUES 
(27, 1000, SYSDATE - 1, '현재 조치 중입니다. 조속한 완료를 위해 노력하겠습니다.');
INSERT INTO TB_INCONVINIENCE_BOARD_REPLY (BOARD_NO, WRITER, WRITE_DATE, COMMENT_CONTENT) VALUES 
(28, 1001, SYSDATE - 2, '빠른 시일 내에 조치될 수 있도록 노력하겠습니다.');
INSERT INTO TB_INCONVINIENCE_BOARD_REPLY (BOARD_NO, WRITER, WRITE_DATE, COMMENT_CONTENT) VALUES 
(10,1002 , SYSDATE - 3, '조치 중이며, 빠른 완료를 위해 노력하고 있습니다.');

commit;

