delete tb_notice;
-- 10개의 더미 데이터 생성 INSERT 문
Insert into C##SSMS.TB_NOTICE (NOTICE_NO, WRITER, NOTICE_TITLE, NOTICE_CONTENT, WRITE_DATE, MODIFY_DATE, READ_COUNT, IMPORTANCY) values (NOTICE_SEQ.NEXTVAL, 1001, '공지사항 1', '이번 주에는 새로운 기능을 추가했습니다.', to_date('2024-04-08','YYYY-MM-DD'), to_date('2024-04-08','YYYY-MM-DD'), 100, '3');
Insert into C##SSMS.TB_NOTICE (NOTICE_NO, WRITER, NOTICE_TITLE, NOTICE_CONTENT, WRITE_DATE, MODIFY_DATE, READ_COUNT, IMPORTANCY) values (NOTICE_SEQ.NEXTVAL, 1002, '중요 공지', '서비스 정상화 안내', to_date('2024-04-07','YYYY-MM-DD'), to_date('2024-04-08','YYYY-MM-DD'), 150, '2');
Insert into C##SSMS.TB_NOTICE (NOTICE_NO, WRITER, NOTICE_TITLE, NOTICE_CONTENT, WRITE_DATE, MODIFY_DATE, READ_COUNT, IMPORTANCY) values (NOTICE_SEQ.NEXTVAL, 1001, '주의: 업데이트 예정', '내일부터 일시적으로 서비스가 중단될 예정입니다.', to_date('2024-04-06','YYYY-MM-DD'), to_date('2024-04-07','YYYY-MM-DD'), 200, '1');
Insert into C##SSMS.TB_NOTICE (NOTICE_NO, WRITER, NOTICE_TITLE, NOTICE_CONTENT, WRITE_DATE, MODIFY_DATE, READ_COUNT, IMPORTANCY) values (NOTICE_SEQ.NEXTVAL, 1004, '긴급 공지', '시스템 장애로 인해 서비스가 중단됩니다. 조속히 복구하겠습니다.', to_date('2024-04-05','YYYY-MM-DD'), to_date('2024-04-06','YYYY-MM-DD'), 300, '3');
Insert into C##SSMS.TB_NOTICE (NOTICE_NO, WRITER, NOTICE_TITLE, NOTICE_CONTENT, WRITE_DATE, MODIFY_DATE, READ_COUNT, IMPORTANCY) values (NOTICE_SEQ.NEXTVAL, 1001, '필독: 서비스 이용 안내', '새로운 서비스 정책이 시행됩니다. 모두 확인해주세요.', to_date('2024-04-04','YYYY-MM-DD'), to_date('2024-04-05','YYYY-MM-DD'), 250, '2');
Insert into C##SSMS.TB_NOTICE (NOTICE_NO, WRITER, NOTICE_TITLE, NOTICE_CONTENT, WRITE_DATE, MODIFY_DATE, READ_COUNT, IMPORTANCY) values (NOTICE_SEQ.NEXTVAL, 1000, '주말 서비스 점검 안내', '주말 동안 서비스 점검이 진행될 예정입니다.', to_date('2024-04-03','YYYY-MM-DD'), to_date('2024-04-04','YYYY-MM-DD'), 180, '1');
Insert into C##SSMS.TB_NOTICE (NOTICE_NO, WRITER, NOTICE_TITLE, NOTICE_CONTENT, WRITE_DATE, MODIFY_DATE, READ_COUNT, IMPORTANCY) values (NOTICE_SEQ.NEXTVAL, 1002, '긴급공지: 시스템 업그레이드', '내일 새벽 2시부터 시스템 업그레이드 작업이 진행될 예정입니다.', to_date('2024-04-02','YYYY-MM-DD'), to_date('2024-04-03','YYYY-MM-DD'), 220, '3');
Insert into C##SSMS.TB_NOTICE (NOTICE_NO, WRITER, NOTICE_TITLE, NOTICE_CONTENT, WRITE_DATE, MODIFY_DATE, READ_COUNT, IMPORTANCY) values (NOTICE_SEQ.NEXTVAL, 1005, '주요 변경사항 안내', '서비스 이용 방법이 변경되었습니다. 자세한 내용은 홈페이지를 참조해주세요.', to_date('2024-04-01','YYYY-MM-DD'), to_date('2024-04-02','YYYY-MM-DD'), 170, '2');
Insert into C##SSMS.TB_NOTICE (NOTICE_NO, WRITER, NOTICE_TITLE, NOTICE_CONTENT, WRITE_DATE, MODIFY_DATE, READ_COUNT, IMPORTANCY) values (NOTICE_SEQ.NEXTVAL, 1001, '서비스 이용 시 유의사항', '서비스 이용 시 개인정보 보호에 유의하세요.', to_date('2024-03-31','YYYY-MM-DD'), to_date('2024-04-01','YYYY-MM-DD'), 190, '1');
Insert into C##SSMS.TB_NOTICE (NOTICE_NO, WRITER, NOTICE_TITLE, NOTICE_CONTENT, WRITE_DATE, MODIFY_DATE, READ_COUNT, IMPORTANCY) values (NOTICE_SEQ.NEXTVAL, 1005, '서비스 업데이트 공지', '서비스 업데이트를 완료했습니다. 새로운 기능을 즐겨보세요.', to_date('2024-03-30','YYYY-MM-DD'), to_date('2024-03-31','YYYY-MM-DD'), 210, '3');
-- 추가로 10개의 더미 데이터 생성 INSERT 문
Insert into C##SSMS.TB_NOTICE (NOTICE_NO, WRITER, NOTICE_TITLE, NOTICE_CONTENT, WRITE_DATE, MODIFY_DATE, READ_COUNT, IMPORTANCY) values (NOTICE_SEQ.NEXTVAL, 1000, '서비스 이용 안내', '서비스 이용 시간이 변경되었습니다. 새로운 시간에 맞춰 이용해주세요.', to_date('2024-03-29','YYYY-MM-DD'), to_date('2024-03-30','YYYY-MM-DD'), 220, '2');
Insert into C##SSMS.TB_NOTICE (NOTICE_NO, WRITER, NOTICE_TITLE, NOTICE_CONTENT, WRITE_DATE, MODIFY_DATE, READ_COUNT, IMPORTANCY) values (NOTICE_SEQ.NEXTVAL, 1004, '서비스 장애 안내', '일시적인 서비스 장애로 불편을 드려 죄송합니다. 최대한 빠른 시일 내에 복구하겠습니다.', to_date('2024-03-28','YYYY-MM-DD'), to_date('2024-03-29','YYYY-MM-DD'), 180, '1');
Insert into C##SSMS.TB_NOTICE (NOTICE_NO, WRITER, NOTICE_TITLE, NOTICE_CONTENT, WRITE_DATE, MODIFY_DATE, READ_COUNT, IMPORTANCY) values (NOTICE_SEQ.NEXTVAL, 1002, '주말 휴무 안내', '다음 주 주말은 휴무입니다. 이 점 참고하시어 이용 부탁드립니다.', to_date('2024-03-27','YYYY-MM-DD'), to_date('2024-03-28','YYYY-MM-DD'), 250, '3');
Insert into C##SSMS.TB_NOTICE (NOTICE_NO, WRITER, NOTICE_TITLE, NOTICE_CONTENT, WRITE_DATE, MODIFY_DATE, READ_COUNT, IMPORTANCY) values (NOTICE_SEQ.NEXTVAL, 1004, '기술 지원 센터 운영 안내', '기술 지원 센터의 운영시간이 변경되었습니다. 자세한 내용은 공지를 참고해주세요.', to_date('2024-03-26','YYYY-MM-DD'), to_date('2024-03-27','YYYY-MM-DD'), 300, '2');
Insert into C##SSMS.TB_NOTICE (NOTICE_NO, WRITER, NOTICE_TITLE, NOTICE_CONTENT, WRITE_DATE, MODIFY_DATE, READ_COUNT, IMPORTANCY) values (NOTICE_SEQ.NEXTVAL, 1001, '정기 점검 안내', '다음 주에 정기 점검이 예정되어 있습니다. 이용에 참고하시기 바랍니다.', to_date('2024-03-25','YYYY-MM-DD'), to_date('2024-03-26','YYYY-MM-DD'), 210, '1');
Insert into C##SSMS.TB_NOTICE (NOTICE_NO, WRITER, NOTICE_TITLE, NOTICE_CONTENT, WRITE_DATE, MODIFY_DATE, READ_COUNT, IMPORTANCY) values (NOTICE_SEQ.NEXTVAL, 1000, '서비스 이용 방법 안내', '새로운 기능 사용 방법에 대한 안내입니다. 자세한 내용은 홈페이지를 참조해주세요.', to_date('2024-03-24','YYYY-MM-DD'), to_date('2024-03-25','YYYY-MM-DD'), 270, '3');
Insert into C##SSMS.TB_NOTICE (NOTICE_NO, WRITER, NOTICE_TITLE, NOTICE_CONTENT, WRITE_DATE, MODIFY_DATE, READ_COUNT, IMPORTANCY) values (NOTICE_SEQ.NEXTVAL, 1002, '새로운 기능 출시', '오늘부로 새로운 기능을 출시했습니다. 이용해보세요!', to_date('2024-03-23','YYYY-MM-DD'), to_date('2024-03-24','YYYY-MM-DD'), 190, '2');
Insert into C##SSMS.TB_NOTICE (NOTICE_NO, WRITER, NOTICE_TITLE, NOTICE_CONTENT, WRITE_DATE, MODIFY_DATE, READ_COUNT, IMPORTANCY) values (NOTICE_SEQ.NEXTVAL, 1003, '서비스 업그레이드 예정', '다음 주에 서비스 업그레이드 작업이 있을 예정입니다. 이용에 불편을 드려 죄송합니다.', to_date('2024-03-22','YYYY-MM-DD'), to_date('2024-03-23','YYYY-MM-DD'), 230, '1');
Insert into C##SSMS.TB_NOTICE (NOTICE_NO, WRITER, NOTICE_TITLE, NOTICE_CONTENT, WRITE_DATE, MODIFY_DATE, READ_COUNT, IMPORTANCY) values (NOTICE_SEQ.NEXTVAL, 1001, '서비스 이용 안내', '서비스 이용 중 발생한 문제 해결을 위한 안내입니다. 자세한 내용은 홈페이지를 참조해주세요.', to_date('2024-03-21','YYYY-MM-DD'), to_date('2024-03-22','YYYY-MM-DD'), 240, '3');
Insert into C##SSMS.TB_NOTICE (NOTICE_NO, WRITER, NOTICE_TITLE, NOTICE_CONTENT, WRITE_DATE, MODIFY_DATE, READ_COUNT, IMPORTANCY) values (NOTICE_SEQ.NEXTVAL, 1003, '서비스 이용 안내', '서비스 이용 방법에 대한 안내입니다. 자세한 내용은 홈페이지를 참조해주세요.', to_date('2024-03-20','YYYY-MM-DD'), to_date('2024-03-21','YYYY-MM-DD'), 260, '2');
-- 추가로 10개의 더미 데이터 생성 INSERT 문
Insert into C##SSMS.TB_NOTICE (NOTICE_NO, WRITER, NOTICE_TITLE, NOTICE_CONTENT, WRITE_DATE, MODIFY_DATE, READ_COUNT, IMPORTANCY) values (NOTICE_SEQ.NEXTVAL, 1000, '서비스 장애 안내', '현재 서비스에 장애가 발생하여 빠른 시일 내에 해결하겠습니다. 이용에 불편을 드려 죄송합니다.', to_date('2024-03-19','YYYY-MM-DD'), to_date('2024-03-20','YYYY-MM-DD'), 180, '1');
Insert into C##SSMS.TB_NOTICE (NOTICE_NO, WRITER, NOTICE_TITLE, NOTICE_CONTENT, WRITE_DATE, MODIFY_DATE, READ_COUNT, IMPORTANCY) values (NOTICE_SEQ.NEXTVAL, 1003, '새로운 기능 출시', '새로운 기능을 출시하였습니다. 이용자 여러분들의 많은 관심 부탁드립니다.', to_date('2024-03-18','YYYY-MM-DD'), to_date('2024-03-19','YYYY-MM-DD'), 220, '2');
Insert into C##SSMS.TB_NOTICE (NOTICE_NO, WRITER, NOTICE_TITLE, NOTICE_CONTENT, WRITE_DATE, MODIFY_DATE, READ_COUNT, IMPORTANCY) values (NOTICE_SEQ.NEXTVAL, 1002, '주요 업데이트 예고', '다음 주에 주요한 업데이트가 예정되어 있습니다. 기대해주시기 바랍니다.', to_date('2024-03-17','YYYY-MM-DD'), to_date('2024-03-18','YYYY-MM-DD'), 250, '3');
Insert into C##SSMS.TB_NOTICE (NOTICE_NO, WRITER, NOTICE_TITLE, NOTICE_CONTENT, WRITE_DATE, MODIFY_DATE, READ_COUNT, IMPORTANCY) values (NOTICE_SEQ.NEXTVAL, 1001, '시스템 점검 안내', '서비스 시스템 점검으로 인해 일시적인 접속이 불가능할 수 있습니다. 양해 부탁드립니다.', to_date('2024-03-16','YYYY-MM-DD'), to_date('2024-03-17','YYYY-MM-DD'), 200, '1');
Insert into C##SSMS.TB_NOTICE (NOTICE_NO, WRITER, NOTICE_TITLE, NOTICE_CONTENT, WRITE_DATE, MODIFY_DATE, READ_COUNT, IMPORTANCY) values (NOTICE_SEQ.NEXTVAL, 1000, '이용약관 변경', '이용약관이 변경되었습니다. 변경된 내용을 확인하시고 동의해주세요.', to_date('2024-03-15','YYYY-MM-DD'), to_date('2024-03-16','YYYY-MM-DD'), 240, '2');
Insert into C##SSMS.TB_NOTICE (NOTICE_NO, WRITER, NOTICE_TITLE, NOTICE_CONTENT, WRITE_DATE, MODIFY_DATE, READ_COUNT, IMPORTANCY) values (NOTICE_SEQ.NEXTVAL, 1003, '서비스 업데이트 안내', '새로운 기능을 추가한 업데이트가 있습니다. 자세한 내용은 공지를 참고해주세요.', to_date('2024-03-14','YYYY-MM-DD'), to_date('2024-03-15','YYYY-MM-DD'), 280, '3');
Insert into C##SSMS.TB_NOTICE (NOTICE_NO, WRITER, NOTICE_TITLE, NOTICE_CONTENT, WRITE_DATE, MODIFY_DATE, READ_COUNT, IMPORTANCY) values (NOTICE_SEQ.NEXTVAL, 1002, '서비스 이용 안내', '서비스 이용 중 발생한 문제를 해결하였습니다. 이용에 불편을 드려 죄송합니다.', to_date('2024-03-13','YYYY-MM-DD'), to_date('2024-03-14','YYYY-MM-DD'), 260, '2');
Insert into C##SSMS.TB_NOTICE (NOTICE_NO, WRITER, NOTICE_TITLE, NOTICE_CONTENT, WRITE_DATE, MODIFY_DATE, READ_COUNT, IMPORTANCY) values (NOTICE_SEQ.NEXTVAL, 1003, '이용권 구매 안내', '이용권을 구매하면 추가 혜택이 있습니다. 자세한 내용은 이용권 페이지를 확인해주세요.', to_date('2024-03-12','YYYY-MM-DD'), to_date('2024-03-13','YYYY-MM-DD'), 230, '1');
Insert into C##SSMS.TB_NOTICE (NOTICE_NO, WRITER, NOTICE_TITLE, NOTICE_CONTENT, WRITE_DATE, MODIFY_DATE, READ_COUNT, IMPORTANCY) values (NOTICE_SEQ.NEXTVAL, 1001, '서비스 이용 방법 안내', '새로운 기능 사용 방법에 대한 안내입니다. 자세한 내용은 공지를 참고해주세요.', to_date('2024-03-11','YYYY-MM-DD'), to_date('2024-03-12','YYYY-MM-DD'), 290, '3');
Insert into C##SSMS.TB_NOTICE (NOTICE_NO, WRITER, NOTICE_TITLE, NOTICE_CONTENT, WRITE_DATE, MODIFY_DATE, READ_COUNT, IMPORTANCY) values (NOTICE_SEQ.NEXTVAL, 1000, '공지사항 안내', '서비스 이용과 관련된 공지사항입니다. 이용자 여러분의 이해와 협조를 부탁드립니다.', to_date('2024-03-10','YYYY-MM-DD'), to_date('2024-03-11','YYYY-MM-DD'), 270, '2');
commit;