delete tb_subscribe;
delete tb_subscribe_payment;
-- 더미 데이터 생성 INSERT 문 (숫자만)
Insert into C##SSMS.TB_SUBSCRIBE (SUBSCRIBE_NO, SUBSCRIBE_NAME, PRICE, SUBSCRIBE_DATE) values (SUBSCRIBE_SEQ.NEXTVAL, 'Basic Plan', 10000, 3);
Insert into C##SSMS.TB_SUBSCRIBE (SUBSCRIBE_NO, SUBSCRIBE_NAME, PRICE, SUBSCRIBE_DATE) values (SUBSCRIBE_SEQ.NEXTVAL, 'Standard Plan', 20000, 6);
Insert into C##SSMS.TB_SUBSCRIBE (SUBSCRIBE_NO, SUBSCRIBE_NAME, PRICE, SUBSCRIBE_DATE) values (SUBSCRIBE_SEQ.NEXTVAL, 'Premium Plan', 30000, 12);
Insert into C##SSMS.TB_SUBSCRIBE (SUBSCRIBE_NO, SUBSCRIBE_NAME, PRICE, SUBSCRIBE_DATE) values (SUBSCRIBE_SEQ.NEXTVAL, 'Gold Plan', 40000, 24);
Insert into C##SSMS.TB_SUBSCRIBE (SUBSCRIBE_NO, SUBSCRIBE_NAME, PRICE, SUBSCRIBE_DATE) values (SUBSCRIBE_SEQ.NEXTVAL, 'Platinum Plan', 50000, 36);
Insert into C##SSMS.TB_SUBSCRIBE (SUBSCRIBE_NO, SUBSCRIBE_NAME, PRICE, SUBSCRIBE_DATE) values (SUBSCRIBE_SEQ.NEXTVAL, 'Trial Plan', 0, 1);
Insert into C##SSMS.TB_SUBSCRIBE (SUBSCRIBE_NO, SUBSCRIBE_NAME, PRICE, SUBSCRIBE_DATE) values (SUBSCRIBE_SEQ.NEXTVAL, 'Family Plan', 60000, 12);
Insert into C##SSMS.TB_SUBSCRIBE (SUBSCRIBE_NO, SUBSCRIBE_NAME, PRICE, SUBSCRIBE_DATE) values (SUBSCRIBE_SEQ.NEXTVAL, 'Student Plan', 8000, 6);
Insert into C##SSMS.TB_SUBSCRIBE (SUBSCRIBE_NO, SUBSCRIBE_NAME, PRICE, SUBSCRIBE_DATE) values (SUBSCRIBE_SEQ.NEXTVAL, 'Corporate Plan', 100000, 24);
Insert into C##SSMS.TB_SUBSCRIBE (SUBSCRIBE_NO, SUBSCRIBE_NAME, PRICE, SUBSCRIBE_DATE) values (SUBSCRIBE_SEQ.NEXTVAL, 'VIP Plan', 120000, 12);
-- 더미 데이터 생성 INSERT 문
Insert into C##SSMS.TB_SUBSCRIBE_PAYMENT (PAY_NO, SUBSCRIBE_NAME, AMOUNT, USER_ID, PAY_METHOD, PAY_DATE) values (SUBSCRIBE_PAYMENT_SEQ, 'Basic Plan', 10000, 1, 'Credit Card', SYSDATE);
Insert into C##SSMS.TB_SUBSCRIBE_PAYMENT (PAY_NO, SUBSCRIBE_NAME, AMOUNT, USER_ID, PAY_METHOD, PAY_DATE) values (SUBSCRIBE_PAYMENT_SEQ, 'Standard Plan', 20000, 2, 'PayPal', SYSDATE);
Insert into C##SSMS.TB_SUBSCRIBE_PAYMENT (PAY_NO, SUBSCRIBE_NAME, AMOUNT, USER_ID, PAY_METHOD, PAY_DATE) values (SUBSCRIBE_PAYMENT_SEQ, 'Premium Plan', 30000, 3, 'Credit Card', SYSDATE);
Insert into C##SSMS.TB_SUBSCRIBE_PAYMENT (PAY_NO, SUBSCRIBE_NAME, AMOUNT, USER_ID, PAY_METHOD, PAY_DATE) values (SUBSCRIBE_PAYMENT_SEQ, 'Gold Plan', 40000, 4, 'Bank Transfer', SYSDATE);
Insert into C##SSMS.TB_SUBSCRIBE_PAYMENT (PAY_NO, SUBSCRIBE_NAME, AMOUNT, USER_ID, PAY_METHOD, PAY_DATE) values (SUBSCRIBE_PAYMENT_SEQ, 'Platinum Plan', 50000, 5, 'Credit Card', SYSDATE);
Insert into C##SSMS.TB_SUBSCRIBE_PAYMENT (PAY_NO, SUBSCRIBE_NAME, AMOUNT, USER_ID, PAY_METHOD, PAY_DATE) values (SUBSCRIBE_PAYMENT_SEQ, 'Trial Plan', 0, 6, 'Free Trial', SYSDATE);
Insert into C##SSMS.TB_SUBSCRIBE_PAYMENT (PAY_NO, SUBSCRIBE_NAME, AMOUNT, USER_ID, PAY_METHOD, PAY_DATE) values (SUBSCRIBE_PAYMENT_SEQ, 'Family Plan', 60000, 7, 'Credit Card', SYSDATE);
Insert into C##SSMS.TB_SUBSCRIBE_PAYMENT (PAY_NO, SUBSCRIBE_NAME, AMOUNT, USER_ID, PAY_METHOD, PAY_DATE) values (SUBSCRIBE_PAYMENT_SEQ, 'Student Plan', 8000, 8, 'PayPal', SYSDATE);
Insert into C##SSMS.TB_SUBSCRIBE_PAYMENT (PAY_NO, SUBSCRIBE_NAME, AMOUNT, USER_ID, PAY_METHOD, PAY_DATE) values (SUBSCRIBE_PAYMENT_SEQ, 'Corporate Plan', 100000, 9, 'Credit Card', SYSDATE);
Insert into C##SSMS.TB_SUBSCRIBE_PAYMENT (PAY_NO, SUBSCRIBE_NAME, AMOUNT, USER_ID, PAY_METHOD, PAY_DATE) values (SUBSCRIBE_PAYMENT_SEQ, 'VIP Plan', 120000, 10, 'Credit Card', SYSDATE);

commit;